### ISSUE TITLE
Add ability to set maintainer approval for an attachment

### ISSUE THREAD

**Issue by Duffyx** [gonzoua/scarab#1]
Hi,

I'm trying to use the tool in order to facilitate my workflow for updating ports.

Example PR created: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240671

Right now we have to touch a PR twice (well actually three times) from a maintainer point of view:
1) Create the PR with subject, and template, with the submit directive
2) Attach the patch to it, with the attach directive
3) Set maintainer approval for the attachment -> currently not possible

Feature request: make it possible to set maintainer approval for a file that will be attached to a PR (make it an option for the attach directive).

I hope its correct what I"m saying, if I overlooked something feel free to tell me :-).

**Comment by gonzoua** [comment]
Hi,

Yes, this functionality is missing in the tool. I started adding flags support.

**Comment by Duffyx** [comment]
Thanks! Feel free to bump when you think its ready to be tested, would be happy to do it.

**Comment by gonzoua** [comment]
I think it's ready for testing now. There are two new sets of commands: flags/addflag/setflag/rmflags and aflags/addaflag/setaflag/rmaflags that manage bug flags and attachment flags respectively. Usage description is available in README and in help.

I didn't find nice way to provide flags during submitting/attaching. The problem there is how to pair flag with requestee. To do this you need to invent a special syntax to pair flag name with username. It felt a bit of an overkill. Instead I added batch mode to make two steps scriptable. The script may look like this:

```  
bug=$(scarab submit -b ...)
scarab addflag $bug exp-run
attach=$(scarab attach -b ...)
scarab addaflag $attach maintainer-approval gonzo@FreeBSD.org
```

Please let me know if this can be used for your workflow.

**Comment by Duffyx** [comment]
Hi, I havent forgotten about this, just didn’t have a port to update which I am maintainer of to put the flag. I saw that a new scarab version was released, will test with that port update. Thanks!

**Comment by Duffyx** [comment]
Ok cool, works just fine! Although I still think it would be nice to have some sort of glue between submitting and instantly attaching and approving a patch. Although whats implemented ATM works just fine, close for now. Thanks!
